### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by DrMabuse23** [electrode-io/generator-electrode#47]
Hey is it possible to sass-loader too ?

**Comment by ananavati** [comment]
Electrode inherently will have support for the latest/next-gen/cutting-edge CSS solutions => CSS Modules + PostCSS, please refer to my previous comment here on the issue: https://github.com/electrode-io/generator-electrode/issues/45#issuecomment-256764412

We are currently working on feature to allow extending webpack configs which will allow for enabling SASS/Flow/etc.. 

feature extending webpack configs: https://github.com/electrode-io/electrode-archetype-react-app/issues/19

this issue #47 is duplicate of: https://github.com/electrode-io/electrode-archetype-react-app/issues/28

can we please close this issue so that the conversation can exist in one place for future reference and ease-of-search.

**Comment by DrMabuse23** [comment]
OK thx

**Comment by dan3721** [comment]
Is there an ETA on the Sass support?
